package com.frissbi.app.enums;

/**
 * Created by thrymr on 2/2/17.
 */

public enum NotificationType {

    FRIEND_PENDING_REQUESTS, FRIEND_REQUEST_ACCEPTANCE, MEETING_PENDING_REQUESTS, MEETING_REQUEST_ACCEPTANCE,
    MEETING_TIME_CHANGED, MEETING_PLACE_CHANGED, MEETING_REJECTED, MEETING_SUMMARY,MEETING_LOCATION_SUGGESTION,ADDED_TO_GROUP;

}
